# -*- coding: utf-8 -*-
"""test_inference.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GaiTogj5TjvnLX4rfYeC9uRMhOu028f-
"""

from google.colab import drive
drive.mount('/content/drive')

!pip install transformers accelerate peft bitsandbytes
!pip install llama-cpp-python
!pip install pandas psutil

BASE_MODEL = "Qwen/Qwen2.5-1.5B-Instruct"

ADAPTER_PATH = "/content/drive/MyDrive/WEEK-8/adapters"

GGUF_MODEL = "/content/drive/MyDrive/WEEK-8/quantized_models/model-q8_0.gguf"

import torch
import time
import pandas as pd
import psutil

from transformers import AutoTokenizer, AutoModelForCausalLM
from peft import PeftModel

tokenizer = AutoTokenizer.from_pretrained(BASE_MODEL)

base_model = AutoModelForCausalLM.from_pretrained(
    BASE_MODEL,
    device_map="auto",
    torch_dtype=torch.float16
)

base_model.eval()

finetuned_model = PeftModel.from_pretrained(
    base_model,
    ADAPTER_PATH
)

finetuned_model.eval()

from llama_cpp import Llama

gguf_model = Llama(
    model_path=GGUF_MODEL,
    n_ctx=2048
)

prompts = [
    "What is bipolar disorder?",
    "Why should patients with suspected major depressive disorder be screened for manic episodes?",
    "Explain peripheral arterial disease treatment.",
    "What is zero order drug elimination?",
    "What hormonal imbalance occurs in polycystic ovarian syndrome?"
]

import time
import torch

def benchmark_transformer(model, tokenizer, prompts):

    total_latency = 0
    total_tokens = 0

    torch.cuda.empty_cache()

    start_vram = torch.cuda.memory_allocated() if torch.cuda.is_available() else 0

    for prompt in prompts:

        inputs = tokenizer(prompt, return_tensors="pt").to(model.device)

        start = time.time()

        with torch.no_grad():
            outputs = model.generate(
                **inputs,
                max_new_tokens=120
            )

        end = time.time()

        latency = end - start

        generated_tokens = outputs.shape[-1] - inputs["input_ids"].shape[-1]

        total_latency += latency
        total_tokens += generated_tokens

    end_vram = torch.cuda.memory_allocated() if torch.cuda.is_available() else 0

    avg_latency = total_latency / len(prompts)
    tokens_per_sec = total_tokens / total_latency
    vram_used = (end_vram - start_vram) / (1024**2)

    return avg_latency, tokens_per_sec, vram_used

#base model benchmark
base_latency, base_tps, base_vram = benchmark_transformer(
    base_model,
    tokenizer,
    prompts
)

finetune_latency, finetune_tps, finetune_vram = benchmark_transformer(
    finetuned_model,
    tokenizer,
    prompts
)

def benchmark_gguf(model, prompts):

    total_latency = 0
    total_tokens = 0

    for prompt in prompts:

        start = time.time()

        output = model(
            prompt,
            max_tokens=120
        )

        end = time.time()

        latency = end - start
        tokens = output["usage"]["completion_tokens"]

        total_latency += latency
        total_tokens += tokens

    avg_latency = total_latency / len(prompts)
    tokens_per_sec = total_tokens / total_latency

    return avg_latency, tokens_per_sec


gguf_latency, gguf_tps = benchmark_gguf(gguf_model, prompts)
gguf_vram = 0  # CPU inference

test_set = [
    ("What is bipolar disorder?", "manic"),
    ("What drug therapy reduces PAD mortality?", "statin"),
    ("What staining detects iron in tissues?", "prussian"),
]

def evaluate_accuracy(model, tokenizer, test_set):

    correct = 0

    for q, keyword in test_set:

        inputs = tokenizer(q, return_tensors="pt").to(model.device)

        with torch.no_grad():
            outputs = model.generate(**inputs, max_new_tokens=80)

        text = tokenizer.decode(outputs[0], skip_special_tokens=True).lower()

        if keyword in text:
            correct += 1

    return correct / len(test_set)

base_acc = evaluate_accuracy(base_model, tokenizer, test_set)
finetune_acc = evaluate_accuracy(finetuned_model, tokenizer, test_set)

def evaluate_accuracy_gguf(model, test_set):

    correct = 0

    for q, keyword in test_set:

        out = model(q, max_tokens=80)

        text = out["choices"][0]["text"].lower()

        if keyword in text:
            correct += 1

    return correct / len(test_set)

gguf_acc = evaluate_accuracy_gguf(gguf_model, test_set)

batch_inputs = tokenizer(prompts, return_tensors="pt", padding=True).to(base_model.device)

with torch.no_grad():
    batch_outputs = base_model.generate(
        **batch_inputs,
        max_new_tokens=80
    )

batch_results = tokenizer.batch_decode(batch_outputs, skip_special_tokens=True)

batch_results

for chunk in gguf_model(
    "Explain peripheral arterial disease.",
    max_tokens=100,
    stream=True
):
    print(chunk["choices"][0]["text"], end="", flush=True)

import pandas as pd

benchmark_table = pd.DataFrame({
    "Model": ["Base", "Fine-tuned", "GGUF"],
    "Latency (s)": [base_latency, finetune_latency, gguf_latency],
    "Tokens/sec": [base_tps, finetune_tps, gguf_tps],
    "VRAM (MB)": [base_vram, finetune_vram, gguf_vram],
    "Accuracy": [base_acc, finetune_acc, gguf_acc],
    "Device": ["CPU", "CPU", "CPU"]
})

benchmark_table

import psutil

ram = psutil.Process().memory_info().rss / (1024**2)
print("RAM usage (MB):", ram)

